repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.0
    hooks:
    -   id: flake8
        additional_dependencies: ["flake8-bugbear"]

      #-   repo: https://github.com/pycqa/isort
      #    rev: 4.1.0
      #    hooks:
      #    -   id: isort
