name: Main
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/CodeQuality.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  test-selenium-scraper:
    name: Test Scrapers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install
        run: sudo pip3 install -r requirements.txt && mkdir -p log/screenshots

      - name: Run test
        run: pytest tests --ignore tests/test_cloud_based_scraper.py

      - name: Save Log
        if: success() || failure()
        run: tar -czvf log.tar.gz log

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: log-report
          path: log.tar.gz
